spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://192.168.1.104:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql:true # 打印日志
#mysql 3.7.5
server:
  context-path: /sell   #url的前缀
  port: 8085
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8
#logging:
  #指定控制台输出格式
  #pattern:
  #  console: "%d -+- %msg%n" 
  # 保存在tomcat下spring.log文件
  #path:
  #  /Users/jiangqianghua/Documents/workspace/wxshop/src/main/log/
  #指定保存在wxshop.log文件
  #file: /Users/jiangqianghua/Documents/workspace/wxshop/src/main/log/wxshop.log
  # 指定打印某个类的日志
  #level:
  #  com.ioomc.LoggerTest: debug
  # 要更好的控制日志，还是需要到logback.xml控制  